name: cinema
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # UI
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  easy_date_timeline: ^2.0.4
  smooth_page_indicator: ^1.2.0+3
  # Video
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5
  # Logic
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  # JSON parsing
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  # HTTP Requets
  dio: ^5.7.0
  # Working with env
  flutter_dotenv: ^5.2.1 
  # DI
  get_it: ^8.0.2
  # Log
  talker_flutter: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_bloc_logger: ^4.5.2
  # Local storage
  flutter_secure_storage: ^9.2.2
  # FIle
  path_provider: ^2.1.5
  # Galary saver
  image_gallery_saver: ^2.0.3
  # JWT Decoder
  jwt_decoder: ^2.0.1
  # Router
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env
